#cloud-config
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNp6nHwtXFBNoi2bMesoOBuExdJvrobr3hHJ+IIv0RV4ntcRwOgdtCOcq1PKU+NXNH8Or5thrrv8EQ8lusPBYVLGKOQ7RvzWcgsH9GqVV+IPssL9NNQgmwPdTIjC/NpeVT9CXjrkJDFeJbS9/TqEpDYiP34v4h/YSspyTFaiqwXHoH6BgP1pDO4V+VTff6DpH1fzoNqS1r3wYnwslvH1CKjqkGkmIj1g/mrXVORb6GMKV3yWm9Y9GD4UPH0C6tpnIjcsLrZGMiUGhWht9d7sNM06mWUXyfL9UJu5GpsQ71oq+oIP3iCwAcVvTzO5SNSqyWNgi7HK4so4Ni96783rO7 YL/WARPANDA
